server.port: 22888

# 替换为自己的数据库地址
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timer-task?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    open-in-view: false
    show-sql: false
    properties.hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect






